### ISSUE TITLE
Add mounting a directory from docker, so CSVs can be shared with host

### ISSUE THREAD

**Issue by wilbowma** [atgeller/Wasm-Prechk-Artifact#3]
The syntax for this is annoying; easier if you use docker compose. The following excerpt from the 411 `docker-compose.yml` file mounts the current directory as `/app/workspace` in Docker.
```
version: "3.9"
services:
  cpsc411:
    build: .
    image: cpsc411
    container_name: cpsc411    
    volumes: 
      - ./:/app/workspace
```

We could add a docker compose file, and ensure the scripts output CSVs to a known directory, and do something similar.
